import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faTimes } from '@fortawesome/pro-light-svg-icons';
import {
  faArrowsAltV,
  faBars,
  faCaretDown,
  faCheck,
  faCheckCircle,
  faCircle,
  faDotCircle,
  faExclamation,
  faExclamationTriangle,
  faFile,
  faFileExcel,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faInfoCircle,
  faMinus,
  faPaperclip,
  faPencilAlt,
  faPlus,
  faSortUp,
  faSquare,
  faStepBackward,
  faStepForward,
  faSync,
  faUser,
  faUsers,
} from '@fortawesome/pro-regular-svg-icons';

import {
  faCheckSquare,
  faMinusSquare,
  faStar,
  faStarHalf,
} from '@fortawesome/pro-solid-svg-icons';

library.add(
  faTimes,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faMinusSquare,
  faCircle,
  faStar,
  faStarHalf,
  faInfoCircle,
  faExclamation,
  faExclamationTriangle,
  faSquare,
  faSortUp,
  faBars,
  faCaretDown,
  faCaretDown,
  faDotCircle,
  faPencilAlt,
  faSync,
  faStepBackward,
  faStepForward,
  faArrowsAltV,
  faPaperclip,
  faPlus,
  faMinus,
  faUser,
  faUsers,
  faFile,
  faFileVideo,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFilePdf,
);

const icons = {
  /*vuetify default icons*/
  complete: ['far', 'check'],
  cancel: ['fal', 'times'],
  close: ['fal', 'times'],
  delete: ['fal', 'times'],
  clear: ['fal', 'times'],
  success: ['far', 'check-circle'],
  info: ['far', 'info-circle'],
  warning: ['far', 'exclamation'],
  error: ['far', 'exclamation-triangle'],
  prev: ['far', 'chevron-left'],
  next: ['far', 'chevron-right'],
  checkboxOn: ['fas', 'check-square'],
  checkboxOff: ['far', 'square'],
  checkboxIndeterminate: ['fas', 'minus-square'],
  delimiter: ['fas', 'circle'],
  sort: ['far', 'sort-up'],
  expand: ['far', 'chevron-down'],
  menu: ['far', 'bars'],
  subgroup: ['far', 'caret-down'],
  dropdown: ['far', 'caret-down'],
  radioOn: ['far', 'dot-circle'],
  radioOff: ['far', 'circle'],
  edit: ['far', 'pencil-alt'],
  ratingEmpty: ['far', 'star'],
  ratingFull: ['fas', 'star'],
  ratingHalf: ['fas', 'star-half'],
  loading: ['far', 'sync'],
  first: ['far', 'step-backward'],
  last: ['far', 'step-forward'],
  unfold: ['far', 'arrows-alt-v'],
  file: ['far', 'paperclip'],
  plus: ['far', 'plus'],
  minus: ['far', 'minus'],
  /*custom icons*/

  user: ['far', 'user'],
  users: ['far', 'users'],
  visible: ['far', 'eye'],
  invisible: ['far', 'eye-slash'],
  fileUnknown: ['far', 'file'],
  fileVideo: ['far', 'file-video'],
  fileWord: ['far', 'file-word'],
  fileExcel: ['far', 'file-excel'],
  filePowerpoint: ['far', 'file-powerpoint'],
  filePdf: ['far', 'file-pdf'],
};

export default {
  values: Object.fromEntries(Object.entries(icons).map(([key, icon]) => [key, {
    component: FontAwesomeIcon,
    props: { icon },
  }])),
};
