import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faTimes } from '@fortawesome/pro-light-svg-icons';
import {
  faArrowsAltV,
  faBars,
  faBell,
  faBirthdayCake,
  faBriefcase,
  faBuilding,
  faBusinessTime,
  faCalendarAlt,
  faCar,
  faCaretDown,
  faChartBar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faClock,
  faCog,
  faDotCircle,
  faEnvelope,
  faExclamation,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFax,
  faFile,
  faFileExcel,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFilter,
  faFolder,
  faFolderOpen,
  faGenderless,
  faGlobeEurope,
  faHandshake,
  faHome,
  faHourglassHalf,
  faInfoCircle,
  faList,
  faMapMarkerAlt,
  faMars,
  faMinus,
  faPaperclip,
  faPencilAlt,
  faPhone,
  faPlus,
  faQuestionCircle,
  faSearch,
  faSortUp,
  faSquare,
  faStepBackward,
  faStepForward,
  faSync,
  faTrain,
  faUpload,
  faUser,
  faUsers,
  faUserUnlock,
  faVenus,
} from '@fortawesome/pro-regular-svg-icons';

import {
  faCheckSquare,
  faEllipsisV,
  faHexagon,
  faLockAlt,
  faMinusSquare,
  faStar,
  faStarHalf,
  faTriangle,
  faUnlockAlt,
} from '@fortawesome/pro-solid-svg-icons';

library.add(
  faTimes,
  faCheckSquare,
  faMinusSquare,
  faCircle,
  faStar,
  faStarHalf,
  faCheck,
  faCheckCircle,
  faInfoCircle,
  faExclamation,
  faExclamationTriangle,
  faChevronLeft,
  faChevronRight,
  faSquare,
  faSortUp,
  faChevronDown,
  faBars,
  faCaretDown,
  faCaretDown,
  faDotCircle,
  faCircle,
  faPencilAlt,
  faStar,
  faSync,
  faStepBackward,
  faStepForward,
  faArrowsAltV,
  faPaperclip,
  faPlus,
  faMinus,
  faUser,
  faCog,
  faHome,
  faHandshake,
  faBusinessTime,
  faUsers,
  faBriefcase,
  faChartBar,
  faUpload,
  faFile,
  faFileVideo,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFilePdf,
  faTriangle,
  faHexagon,
  faBell,
  faSearch,
  faCar,
  faTrain,
  faPhone,
  faEnvelope,
  faFax,
  faGlobeEurope,
  faMapMarkerAlt,
  faCalendarAlt,
  faClock,
  faList,
  faBirthdayCake,
  faHourglassHalf,
  faQuestionCircle,
  faEllipsisV,
  faEye,
  faEyeSlash,
  faFolder,
  faFolderOpen,
  faGenderless,
  faMars,
  faVenus,
  faFilter,
  faUserUnlock,
  faBuilding,
  faLockAlt,
  faUnlockAlt,
);

const icons = {
  /*vuetify default icons*/
  complete: ['far', 'check'],
  cancel: ['fal', 'times'],
  close: ['fal', 'times'],
  delete: ['fal', 'times'],
  clear: ['fal', 'times'],
  success: ['far', 'check-circle'],
  info: ['far', 'info-circle'],
  warning: ['far', 'exclamation'],
  error: ['far', 'exclamation-triangle'],
  prev: ['far', 'chevron-left'],
  next: ['far', 'chevron-right'],
  checkboxOn: ['fas', 'check-square'],
  checkboxOff: ['far', 'square'],
  checkboxIndeterminate: ['fas', 'minus-square'],
  delimiter: ['fas', 'circle'],
  sort: ['far', 'sort-up'],
  expand: ['far', 'chevron-down'],
  menu: ['far', 'bars'],
  subgroup: ['far', 'caret-down'],
  dropdown: ['far', 'caret-down'],
  radioOn: ['far', 'dot-circle'],
  radioOff: ['far', 'circle'],
  edit: ['far', 'pencil-alt'],
  ratingEmpty: ['far', 'star'],
  ratingFull: ['fas', 'star'],
  ratingHalf: ['fas', 'star-half'],
  loading: ['far', 'sync'],
  first: ['far', 'step-backward'],
  last: ['far', 'step-forward'],
  unfold: ['far', 'arrows-alt-v'],
  file: ['far', 'paperclip'],
  plus: ['far', 'plus'],
  minus: ['far', 'minus'],
  /*custom icons*/

  profile: ['far', 'user'],
  settings: ['far', 'cog'],
  home: ['far', 'home'],
  notifications: ['far', 'bell'],
  search: ['far', 'search'],
  birthday: ['far', 'birthday-cake'],
  invited: ['far', 'hourglass-half'],
  unknown: ['far', 'question-circle'],
  fabDots: ['fas', 'ellipsis-v'],
  visible: ['far', 'eye'],
  invisible: ['far', 'eye-slash'],
  filter: ['far', 'filter'],

  vacancy: ['far', 'handshake'],
  shift: ['far', 'business-time'],
  candidate: ['far', 'users'],
  employer: ['far', 'briefcase'],
  report: ['far', 'chart-bar'],
  role: ['far', 'user-unlock'],
  location: ['far', 'building'],
  department: ['far', 'building'],
  position: ['far', 'briefcase'],

  upload: ['far', 'upload'],
  fileUnknown: ['far', 'file'],
  fileVideo: ['far', 'file-video'],
  fileWord: ['far', 'file-word'],
  fileExcel: ['far', 'file-excel'],
  filePowerpoint: ['far', 'file-powerpoint'],
  filePdf: ['far', 'file-pdf'],
  folderOpen: ['far', 'folder-open'],
  folderClosed: ['far', 'folder'],

  triangle: ['fas', 'triangle'],
  hexagon: ['fas', 'hexagon'],

  car: ['far', 'car'],
  train: ['far', 'train'],

  phone: ['far', 'phone'],
  email: ['far', 'envelope'],
  fax: ['far', 'fax'],
  website: ['far', 'globe-europe'],
  address: ['far', 'map-marker-alt'],

  date: ['far', 'calendar-alt'],
  time: ['far', 'clock'],

  viewList: ['far', 'list'],
  viewCalendar: ['far', 'calendar-alt'],
  viewChart: ['far', 'chart-bar'],

  genderUnknown: ['far', 'genderless'],
  genderMale: ['far', 'mars'],
  genderFemale: ['far', 'venus'],

  lock: ['fas', 'lock-alt'],
  unlock: ['fas', 'unlock-alt'],
};


export default {
  values: Object.fromEntries(Object.entries(icons).map(([key, icon]) => [key, {
    component: FontAwesomeIcon,
    props: { icon },
  }])),
};
