name: Build & Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

<%_ if (options.plugins.includes('fontawesomepro')) { _%>
      - name: build .npmrc
        env:
          FONT_AWESOME_TOKEN: ${{ secrets.font_awesome_token  }}
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=$FONT_AWESOME_TOKEN" >> .npmrc
<%_ } _%>
      - name: install
        run: |
          npm ci

      - name: lint
        run: |
          npm run lint

      - name: build
        run: |
          npm run build
